service: bombermon

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sdb:PutAttributes"
        - "sdb:Select"
      Resource: "arn:aws:sdb:${self:provider.region}:*:domain/bombermon"
    - Effect: "Allow"
      Action:
        - "iot:DescribeEndpoint"
      Resource: "*"    
    - Effect: "Allow"
      Action:
        - "sts:AssumeRole"
      Resource: "*"      

functions:
  game:
    handler: handler.game
    events:
      - http: GET iot/keys
      - http: POST avatars/available
      - http: PUT avatars/available
      - http: OPTIONS avatars/available